CREATE DATABASE IF NOT EXISTS aviation_project;
CREATE SCHEMA IF NOT EXISTS aviation_project.airlines;

USE DATABASE aviation_project;
USE SCHEMA airlines;



CREATE OR REPLACE FILE FORMAT PARQUET_FF
  TYPE = PARQUET;



DESC INTEGRATION AIRLINES_S3_INT;
SELECT * FROM aviation_project.airlines.BRONZE_AIRLINES_RAW;

-- creating rae tables:
CREATE TABLE BRONZE_AIRLINES_RAW (
  IATA_CODE STRING,
  AIRLINE STRING,
  LOAD_TIMESTAMP TIMESTAMP
);

show integrations;

select * from BRONZE_AIRLINES_RAW;

CREATE TABLE BRONZE_AIRPORTS_RAW (
  IATA_CODE STRING,
  AIRPORT STRING,
  CITY STRING,
  STATE STRING,
  COUNTRY STRING,
  LATITUDE STRING,
  LONGITUDE STRING,
  LOAD_TIMESTAMP TIMESTAMP
);

CREATE TABLE BRONZE_FLIGHTS_SAMPLE_RAW (
  YEAR INT,
  MONTH INT,
  DAY INT,
  DAY_OF_WEEK INT,
  AIRLINE STRING,
  FLIGHT_NUMBER STRING,
  TAIL_NUMBER STRING,
  ORIGIN_AIRPORT STRING,
  DESTINATION_AIRPORT STRING,
  SCHEDULED_DEPARTURE STRING,
  DEPARTURE_TIME STRING,
  DEPARTURE_DELAY STRING,
  TAXI_OUT STRING,
  WHEELS_OFF STRING,
  SCHEDULED_TIME STRING,
  ELAPSED_TIME STRING,
  AIR_TIME STRING,
  DISTANCE INT,
  WHEELS_ON STRING,
  TAXI_IN STRING,
  SCHEDULED_ARRIVAL STRING,
  ARRIVAL_TIME STRING,
  ARRIVAL_DELAY STRING,
  DIVERTED STRING,
  CANCELLED STRING,
  CANCELLATION_REASON STRING,
  AIR_SYSTEM_DELAY STRING,
  SECURITY_DELAY STRING,
  AIRLINE_DELAY STRING,
  LATE_AIRCRAFT_DELAY STRING,
  WEATHER_DELAY STRING,
  LOAD_TIMESTAMP TIMESTAMP
);




-- Integration
CREATE OR REPLACE STORAGE INTEGRATION AIRLINES_S3_INT
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = S3
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::912868725823:role/snowflake_s3'  
  STORAGE_ALLOWED_LOCATIONS = ('s3://airlines-project2/parquet/');

  DESC INTEGRATION AIRLINES_S3_INT;


-- staging layer
  CREATE OR REPLACE STAGE RAW_STAGE
  STORAGE_INTEGRATION = AIRLINES_S3_INT
  URL = 's3://airlines-project2/parquet/'
  FILE_FORMAT = (TYPE = PARQUET);

  LIST @RAW_STAGE;


-- creatig pipes
CREATE OR REPLACE PIPE PIPE_AIRLINES_RAW
  AUTO_INGEST = TRUE
  AS
  COPY INTO BRONZE_AIRLINES_RAW
  FROM @RAW_STAGE/airlines/
  FILE_FORMAT = (TYPE = PARQUET)
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

ALTER PIPE PIPE_AIRLINES_RAW REFRESH;


CREATE OR REPLACE PIPE PIPE_AIRPORTS_RAW
  AUTO_INGEST = TRUE
  AS
  COPY INTO BRONZE_AIRPORTS_RAW
  FROM @RAW_STAGE/airports/
  FILE_FORMAT = (TYPE = PARQUET)
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

ALTER PIPE PIPE_AIRPORTS_RAW REFRESH;

drop pipe PIPE_FLIGHTS_SAMPLE_RAW;

CREATE OR REPLACE PIPE PIPE_FLIGHTS_SAMPLE_RAW
  AUTO_INGEST = TRUE
  AS
  COPY INTO BRONZE_FLIGHTS_SAMPLE_RAW
  FROM @RAW_STAGE/flights_sample/
  FILE_FORMAT = (TYPE = PARQUET)
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

ALTER PIPE PIPE_FLIGHTS_SAMPLE_RAW REFRESH;


SHOW PIPES;






SELECT * FROM aviation_project.airlines.BRONZE_AIRPORTS_RAW;





select * from aviation_project.airlines.SILVER_AIRLINES;